// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCqbWOH2I1bUvUlSf6iuUmA5Mcr2bV81c',
    appId: '1:24514339128:android:85b0e9c6f6ad8045fb61cd',
    messagingSenderId: '24514339128',
    projectId: 'sage-wave-251008',
    databaseURL: 'https://sage-wave-251008.firebaseio.com',
    storageBucket: 'sage-wave-251008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrcYL0lVqPsfD8zR2Bd_QvMNgrYJ5LRv0',
    appId: '1:24514339128:ios:8aebfe172462b707fb61cd',
    messagingSenderId: '24514339128',
    projectId: 'sage-wave-251008',
    databaseURL: 'https://sage-wave-251008.firebaseio.com',
    storageBucket: 'sage-wave-251008.appspot.com',
    androidClientId: '24514339128-7puhf8723jgna5c9dbqrnnmnr5rsj8ov.apps.googleusercontent.com',
    iosClientId: '24514339128-vhtrmoo28efetcdc8cju0s1q5uhfdlgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.nasaFlutter',
  );
}
